"""Create Product table

Revision ID: 9b9bd52bce62
Revises:
Create Date: 2025-09-04 20:46:30.874987

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "9b9bd52bce62"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",  # type: ignore[attr-defined]
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_name"), "product", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_name"), table_name="product")  # type: ignore[attr-defined]
    op.drop_table("product")
    # ### end Alembic commands ###
